test("our first test", () => {});

test("our second test", () => {
  throw new Error("Something faild");
});
